include:
  - path: sandcat/compose-proxy.yml

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.app
    # Share wg-client's network namespace so all traffic goes through its
    # WireGuard tunnel. The app container has no NET_ADMIN capability,
    # so processes inside cannot modify routing, iptables, or the tunnel.
    network_mode: "service:wg-client"
    volumes:
      # Mount the project's code
      - ..:/workspaces/sandcat:cached
      # Read-only devcontainer directory
      - ../.devcontainer:/workspaces/sandcat/.devcontainer:ro
      # Read-only policy directory
      - ../.sandcat:/workspaces/sandcat/.sandcat:ro
      # Named volume for the home directory so Claude Code auth state,
      # shell history, and other user-level config persist across rebuilds.
      - app-home:/home/vscode
      # Shared volume from mitmproxy containing the CA cert and
      # sandcat.env (env vars + secret placeholders). Read-only — app
      # containers should never write to this.
      - mitmproxy-config:/mitmproxy-config:ro
      # Persist shell history
      - claude-history:/commandhistory
    working_dir: /workspaces/sandcat
    command: sleep infinity
    stdin_open: true
    tty: true
    environment:
      - CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
    depends_on:
      wg-client:
        condition: service_healthy

volumes:
  app-home:
  claude-history:
